version 1.4.0, build 256

diff --git a/lib/swift_wrapper/swiftc b/lib/swift_wrapper/swiftc
--- a/lib/swift_wrapper/swiftc
+++ b/lib/swift_wrapper/swiftc
@@ -1,32 +1,109 @@
 #!/bin/bash
 
-set -e
+unset arch
+extract_args() {
+    while [[ $# -gt 0 ]]
+    do
+    key="$1"
+
+    case $key in
+        -target)
+        arch="$2"
+        shift # past argument
+        ;;
+        *)
+            # unknown option
+        ;;
+    esac
+    shift # past argument or value
+    done
+}
+
+extract_args "$@"
+
+is_debug=`basename "$0"`
+exec 3>/dev/null 4>&3
+if [ "$is_debug" == "swiftc_debug" ]; then
+    echo "running swiftc in debug"
+    set -x
+    exec 3>&1 4>&2
+fi
+
+VAR_DIR=/tmp/rollout_var/swift_injections/"$arch"
+mkdir -p "$VAR_DIR"
+
+originalParams=("$@")
+swift_path=`/usr/bin/xcrun -f swiftc`
+error_file="$VAR_DIR"/swiftc_error
+error_handler() {
+    local check_last_status=$1
+    local last_status=$2
+    local category=$3
+    echo "exec original swiftc" >&3
+    unset ROLLOUT_REPLACEMENTS
+    unset DYLD_FORCE_FLAT_NAMESPACE
+    unset DYLD_INSERT_LIBRARIES
+    "$swift_path" "${originalParams[@]}"
+    local original_status=$?
+    if [[ ("$check_last_status" == "false" && "$original_status" -eq "0") || ("$check_last_status" == "true" && "$original_status" -ne "$last_status") ]]; then 
+       echo "ROLLOUT ERROR: $category"
+       echo "going to send error to Rollout.io"
+       (
+           echo "$error_file"
+           server="$ROLLOUT_allServicesInOneServer"
+           [ -n "$ROLLOUT_allServicesInOneServer" ] || server="https://error.rollout.io"
+           url="$server/build/error/$category"
+           gzip -c "$error_file" | curl -sS --location --post301 --post302 -F data=@"-" "$url" 
+       ) &
+    else
+       echo "OTHER ERROR" >&3
+    fi
+   
+    clean 
+    exit $last_status
+}
+
+clean() {
+    [ -d /tmp/rollout_swiftc_generated_files_debug_location ] && {
+      rm -rf /tmp/rollout_swiftc_generated_files_debug_location/*"$arch"
+      mv "$VAR_DIR" /tmp/rollout_swiftc_generated_files_debug_location/"$arch"
+    } || {
+      rm -rf "$VAR_DIR"
+    }
+}
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-Temp_Files=()
+rollout_replacements_file="$VAR_DIR"/replacements
+rollout_sources_file="$VAR_DIR"/sources
 for i in "$@"
 do
     [[ $i =~ RolloutGenerated\.swift$ ]] && {
-        Rollout_Generated=`mktemp "$i".XXXX`
-        cp $i $Rollout_Generated
-        Rollout_Replacements="$Rollout_Replacements,$i,$Rollout_Generated"
+        last_component=`basename "$i"`
+        Rollout_Generated="$VAR_DIR"/"$last_component"
+        cp "$i" "$Rollout_Generated" 2>$error_file ||  error_handler "false" $? "CopyFiles"
+        echo "$i" >> "$rollout_replacements_file"
+        echo "$Rollout_Generated" >> "$rollout_replacements_file"
         continue;
     }
+
     [[ $i =~ \.swift$ ]] && {
-        TEMP_FILE=`mktemp "$i".XXXX`
-        cp $i $TEMP_FILE
-        Temp_Files+=($TEMP_FILE)
-        Rollout_Replacements="$Rollout_Replacements,$i,$TEMP_FILE"
+        last_component=`basename "$i"`
+        TEMP_FILE="$VAR_DIR"/"$last_component"
+        cp "$i" "$TEMP_FILE" 2>$error_file ||  error_handler "false" $? "CopyFiles"
+        echo "$TEMP_FILE" >> "$rollout_sources_file"
+        echo "$i" >> "$rollout_replacements_file"
+        echo "$TEMP_FILE" >> "$rollout_replacements_file"
     }
 done
 
-Rollout_Replacements="${Rollout_Replacements:1}"
+$DIR/../../lib/Oyster/MacOS/Oyster "$Rollout_Generated" "$rollout_sources_file" >&3 2>$error_file || error_handler "false" $? "Oyster"
 
-"$DIR"/../../Oyster/Build/Products/Debug/Oyster "$Rollout_Generated" "${Temp_Files[@]}" 
+export ROLLOUT_REPLACEMENTS="$rollout_replacements_file"
+export DYLD_FORCE_FLAT_NAMESPACE=1
+export DYLD_INSERT_LIBRARIES=$DIR/../../lib/libRolloutOverrides.dylib
 
-swift_path=`/usr/bin/xcrun -f swiftc`
+"$swift_path" "$@" 2>$error_file || error_handler "true" $? "Compiler" 
+cat $error_file
 
-ROLLOUT_REPLACEMENTS=$Rollout_Replacements DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=$DIR/../../Oyster/lib_overrides.dylib "$swift_path" "$@"
-
-rm $Rollout_Generated "${Temp_Files[@]}"  
+clean
